### ISSUE TITLE
showing toast when failure happen, not works

### ISSUE THREAD

**Issue by navotera** [nisrulz/OptimusHTTP#2]
hai again.. :)

why when i type : 
Toast.makeText(MainActivity.this, "NOT WORK", Toast.LENGTH_SHORT).show();
on failure method it would make my app error ? 
error msg : " Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()"

thanks

**Comment by nisrulz** [comment]
Because you need to call that in the UI thread. Use a handler to run the Toast on the ui thread

**Comment by navotera** [comment]
thanks sir... that my new to do assignment to learn bout handler :+1: 
but as suggestion why not using main thread on failure method ?
