### ISSUE TITLE
Put and delete request missing

### ISSUE THREAD

**Issue by TheZoker** [nisrulz/OptimusHTTP#3]
Hi there,

What about `put` and `delete` requests?
Are these supported? Will you add support for them?

Thank you!

**Comment by nisrulz** [comment]
@TheZoker I will add them soon. They are not supported as of now. 

They are however in the pipeline.

**Comment by nisrulz** [comment]
Closing as issue is resolved in the latest [release v1.1.0](https://github.com/nisrulz/OptimusHTTP/releases/tag/1.1.0)
