### ISSUE TITLE
Timeout response

### ISSUE THREAD

**Issue by Albertorio** [nisrulz/OptimusHTTP#6]
Any way to extend the timeout from 10 seconds to at least 15 seconds?

**Comment by nisrulz** [comment]
Those functionalities aren't open in the current version. But I am thinking of opening all of these in the upcoming version.

**Comment by nisrulz** [comment]
@Albertorio I have released a new version of the lib - `1.2.0` , with the capability to modify the timeout values. Please verify it works for you and then close this issue.

Thank you.

**Comment by Albertorio** [comment]
Sorry for the late response. I updated to the new version but been getting this Error on build:

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

I don't know if its a problem with the packaging of the library or a problem with my dependencies.

**Comment by nisrulz** [comment]
@Albertorio enable multidexing in your app. Probably after you included the lib you exceeded the method count limit of 65K. You can use [Classyshark](https://github.com/google/android-classyshark) to verify your final apk for method counts.

Let me know if its of use.

**Comment by Albertorio** [comment]
I tried multidex, it changed the error to this:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/print/PrintHelper$PrintHelperStubImpl.class

Looking around for a solution I also tried this but didn't work:

  compile ('com.github.nisrulz:optimushttp:1.2.0'){
        exclude module: 'support-v4'
    }

**Comment by nisrulz** [comment]
Well OptimusHttp uses `support-core-utils`  as a dependency
https://github.com/nisrulz/OptimusHTTP/blob/master/optimushttp/build.gradle#L44

So maybe try excluding that specificaly.

**Comment by Albertorio** [comment]
That fixed it, thank you very much. Also remember to change in the usage that the constructor now needs the Activity context and remove the context from the client.makeRequest.
